name: restui
description: Handle your rest queries from widget tree.
version: 0.0.2
author: Kamil Klyta
repository: https://github.com/gonuit/flutter_restui
homepage: https://github.com/gonuit/flutter_restui
issue_tracker: https://github.com/gonuit/flutter_restui/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  provider: ^4.0.3
  http: 0.12.0+4
  meta: 1.1.8
  http_parser: 3.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
