name: restui
description: A simple yet powerful wrapper around http package. 
version: 0.4.0+3
repository: https://github.com/gonuit/flutter_restui
homepage: https://github.com/gonuit/flutter_restui
issue_tracker: https://github.com/gonuit/flutter_restui/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  http: ^0.12.0
  meta: ^1.1.8
  http_parser: ^3.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
