name: restui
description: A simple yet powerful HTTP API client library that main target is to remove separation between HTTP API and app state management
version: 0.2.0+2
repository: https://github.com/gonuit/flutter_restui
homepage: https://github.com/gonuit/flutter_restui
issue_tracker: https://github.com/gonuit/flutter_restui/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  meta: ^1.1.8
  http_parser: ^3.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
