name: restui
description: A simple yet powerful wrapper around `http` library which allows handling middlewares by ApiLink's (strongly inspired by apollo graphQL client)
version: 0.1.0
repository: https://github.com/gonuit/flutter_restui
homepage: https://github.com/gonuit/flutter_restui
issue_tracker: https://github.com/gonuit/flutter_restui/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.12.0
  meta: ^1.1.8
  http_parser: ^3.1.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
